Added command to fix error with old i2c library
Before that I got the error in the basic_motion.ipynb:
TypeError: an integer is required (got type bytearray)